// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYPYmuKu9RwzDqOJ8a1wNDstBa7mH-1cY',
    appId: '1:949507934475:web:4d823d68a90d3ec47c3a0e',
    messagingSenderId: '949507934475',
    projectId: 'language-box-ef8f7',
    authDomain: 'language-box-ef8f7.firebaseapp.com',
    storageBucket: 'language-box-ef8f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf6IS3J4yLJvu5rQUFeK8EHMO-uGJljqQ',
    appId: '1:949507934475:android:4e1c4d6a4cea847a7c3a0e',
    messagingSenderId: '949507934475',
    projectId: 'language-box-ef8f7',
    storageBucket: 'language-box-ef8f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl6OH63DEYXycxxRaBgQvF19eDoTkaWZU',
    appId: '1:949507934475:ios:d757ecd1802d4bb47c3a0e',
    messagingSenderId: '949507934475',
    projectId: 'language-box-ef8f7',
    storageBucket: 'language-box-ef8f7.firebasestorage.app',
    iosClientId: '949507934475-sktii4onjhd0ns07a9misfejf5aoohgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.languagebox',
  );

}